import { CampaignSummary } from "./campaign-types";

export const CAMPAIGNS_DATA: CampaignSummary[] = [
  {
    id: "cmp_1",
    subject: "Reminder: UMak SIC General Assembly this Saturday!",
    eventName: "General Assembly 2026",
    venue: "Audio Visual Room",
    eventDate: "17 Oct 2026 · 2:00 PM",
    sentDate: "14 Oct 2026",
    status: "sent",
    totalStudents: 118,
    deliveredCount: 109,
    sendingCount: 6,
    invalidEmailCount: 3,
    bannerImageName: "general-assembly-banner.jpg",
    attachedFilesCount: 1,
    queueBreakdown: {
      queued: 6,
      sending: 1,
      sent: 109,
      bounced: 1,
      failed: 2,
    },
    providers: [
      {
        provider: "Mailgun",
        role: "primary",
        used: 92,
        total: 100,
        resetTime: "00:00 UTC",
        timezone: "UTC",
        notes: "Daily capacity: 100. Reset period and timezone are stored from provider configuration, not the organisation timezone.",
      },
      {
        provider: "Brevo",
        role: "fallback",
        used: 0,
        total: 300,
        resetTime: "00:00 CET",
        timezone: "Europe/Paris",
        notes: "Daily capacity: 300. Used only after Mailgun capacity is exhausted. Reset contract stored independently.",
      },
    ],
    diagnostics: [
      {
        id: "diag_1",
        recipientName: "Andrea Santos",
        studentId: "2023-00182",
        email: "andrea.santos@umak.edu.ph",
        provider: "Mailgun",
        messageId: "Ref #7D31",
        status: "sent",
        statusDescription: "Delivered to student inbox",
        idempotencyKey: "Protected against duplicates",
        lastAttemptTime: "14 Oct 2026, 09:14 AM",
      },
      {
        id: "diag_2",
        recipientName: "Miguel Dela Cruz",
        studentId: "2023-00491",
        email: "miguel.delacruz@umak.edu.ph",
        provider: "Brevo",
        scheduledRetry: "Tonight at 00:05",
        status: "queued",
        statusDescription: "Waiting for midnight reset window",
        idempotencyKey: "Protected against duplicates",
        lastAttemptTime: "14 Oct 2026, 09:14 AM",
      },
      {
        id: "diag_3",
        recipientName: "Bianca Flores",
        studentId: "2023-00612",
        email: "bianca.flores@umak.edu.ph",
        provider: "Mailgun",
        messageId: "Ref #7D88",
        status: "bounced",
        statusDescription: "Student email inbox is full or unavailable",
        idempotencyKey: "Protected against duplicates",
        lastAttemptTime: "14 Oct 2026, 09:15 AM",
      },
      {
        id: "diag_4",
        recipientName: "Joshua Ramos",
        studentId: "2022-01934",
        email: "joshua.ramos@umak.edu.ph",
        provider: "Mailgun",
        messageId: "Ref #7D33",
        status: "sent",
        statusDescription: "Delivered to student inbox",
        idempotencyKey: "Protected against duplicates",
        lastAttemptTime: "14 Oct 2026, 09:15 AM",
      },
      {
        id: "diag_5",
        recipientName: "Mark Bautista",
        studentId: "2021-03412",
        email: "mark.bautista@umak.edu.ph",
        provider: "Mailgun",
        status: "failed",
        statusDescription: "Please check student email address spelling",
        idempotencyKey: "Protected against duplicates",
        lastAttemptTime: "14 Oct 2026, 09:16 AM",
      },
    ],
    recipients: [
      {
        id: "s1",
        name: "Andrea Santos",
        studentId: "2023-00182",
        email: "andrea.santos@umak.edu.ph",
        course: "BSIT",
        program: "BS Information Technology",
        deliveryStatus: "delivered",
        deliveredAt: "14 Oct 2026, 09:14 AM",
        provider: "Mailgun",
        messageId: "Ref #7D31",
        ticketCode: "SIC-GA-00182",
      },
      {
        id: "s2",
        name: "Miguel Dela Cruz",
        studentId: "2023-00491",
        email: "miguel.delacruz@umak.edu.ph",
        course: "BSCS",
        program: "BS Computer Science",
        deliveryStatus: "delivered",
        deliveredAt: "14 Oct 2026, 09:14 AM",
        provider: "Mailgun",
        messageId: "Ref #7D32",
        ticketCode: "SIC-GA-00491",
      },
      {
        id: "s3",
        name: "Joshua Ramos",
        studentId: "2022-01934",
        email: "joshua.ramos@umak.edu.ph",
        course: "BSIT",
        program: "BS Information Technology",
        deliveryStatus: "delivered",
        deliveredAt: "14 Oct 2026, 09:15 AM",
        provider: "Mailgun",
        messageId: "Ref #7D33",
        ticketCode: "SIC-GA-01934",
      },
      {
        id: "s4",
        name: "Patricia Reyes",
        studentId: "2023-00823",
        email: "patricia.reyes@umak.edu.ph",
        course: "BSCS",
        program: "BS Computer Science",
        deliveryStatus: "delivered",
        deliveredAt: "14 Oct 2026, 09:16 AM",
        provider: "Mailgun",
        messageId: "Ref #7D34",
        ticketCode: "SIC-GA-00823",
      },
      {
        id: "s5",
        name: "Chloe Lim",
        studentId: "2023-01129",
        email: "chloe.lim@umak.edu.ph",
        course: "BSINS",
        program: "BS Information Systems",
        deliveryStatus: "sending",
        statusNote: "Queued for automatic dispatch",
        provider: "Mailgun",
        ticketCode: "SIC-GA-01129",
      },
      {
        id: "s6",
        name: "Daniel Tan",
        studentId: "2022-02104",
        email: "daniel.tan@umak.edu.ph",
        course: "BSIT",
        program: "BS Information Technology",
        deliveryStatus: "sending",
        statusNote: "Locked by background dispatcher",
        provider: "Mailgun",
        ticketCode: "SIC-GA-02104",
      },
      {
        id: "s7",
        name: "Bianca Flores",
        studentId: "2023-00612",
        email: "bianca.flores@umak.edu.ph",
        course: "BSINS",
        program: "BS Information Systems",
        deliveryStatus: "invalid_email",
        statusNote: "Mailbox full or unavailable",
        provider: "Mailgun",
        ticketCode: "SIC-GA-00612",
      },
      {
        id: "s8",
        name: "Mark Bautista",
        studentId: "2021-03412",
        email: "mark.bautista@umak.edu.ph",
        course: "BSCS",
        program: "BS Computer Science",
        deliveryStatus: "invalid_email",
        statusNote: "Check email address spelling",
        provider: "Mailgun",
        ticketCode: "SIC-GA-03412",
      },
    ],
  },
  {
    id: "cmp_2",
    subject: "Workshop Prerequisites & Google Cloud Console Setup",
    eventName: "Cloud Computing 101",
    venue: "CCIS Lab 304",
    eventDate: "23 Oct 2026 · 1:00 PM",
    sentDate: "20 Oct 2026",
    status: "draft",
    totalStudents: 48,
    deliveredCount: 0,
    sendingCount: 0,
    invalidEmailCount: 0,
    attachedFilesCount: 0,
    recipients: [],
  },
  {
    id: "cmp_3",
    subject: "Post-Event Thank You & Official Certificates of Attendance",
    eventName: "Hackathon Orientation",
    venue: "Audio Visual Room",
    eventDate: "10 Sep 2026 · 1:30 PM",
    sentDate: "11 Sep 2026",
    status: "sent",
    totalStudents: 142,
    deliveredCount: 140,
    sendingCount: 0,
    invalidEmailCount: 2,
    attachedFilesCount: 2,
    recipients: [
      {
        id: "s10",
        name: "Samantha Mendoza",
        studentId: "2023-00341",
        email: "samantha.mendoza@umak.edu.ph",
        deliveryStatus: "delivered",
        deliveredAt: "11 Sep 2026, 02:00 PM",
      },
      {
        id: "s11",
        name: "Gabriel Aquino",
        studentId: "2022-01452",
        email: "gabriel.aquino@umak.edu.ph",
        deliveryStatus: "delivered",
        deliveredAt: "11 Sep 2026, 02:01 PM",
      },
    ],
  },
  {
    id: "cmp_4",
    subject: "Venue Change Notice to University Grand Amphitheater",
    eventName: "Student Leadership Summit",
    venue: "University Amphitheater",
    eventDate: "28 Aug 2026 · 8:30 AM",
    sentDate: "27 Aug 2026",
    status: "sent",
    totalStudents: 95,
    deliveredCount: 95,
    sendingCount: 0,
    invalidEmailCount: 0,
    attachedFilesCount: 1,
    recipients: [
      {
        id: "s20",
        name: "Eunice Castro",
        studentId: "2023-01829",
        email: "eunice.castro@umak.edu.ph",
        deliveryStatus: "delivered",
        deliveredAt: "27 Aug 2026, 08:30 AM",
      },
    ],
  },
];

export function getCampaignById(id: string): CampaignSummary | undefined {
  return CAMPAIGNS_DATA.find((c) => c.id === id) || CAMPAIGNS_DATA[0];
}
