import { AssetItem, StorageKpis } from "./asset-types";

export const INITIAL_ASSETS: AssetItem[] = [
  {
    id: "ast_1",
    objectKey: "assets/banners/general-assembly-header.jpg",
    originalFilename: "general-assembly-header.jpg",
    mediaType: "image/jpeg",
    format: "jpg",
    category: "image",
    byteSize: 1887436,
    fileSizeFormatted: "1.8 MB",
    uploadedBy: "Charles Reyes",
    uploadedAt: "14 Oct 2026, 09:30 AM",
    dimensions: "1200 × 400 px",
    sha256Hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    url: "/assets/events/event-ga.png",
    previewUrl: "/assets/events/event-ga.png",
    downloadCount: 42,
    references: [
      {
        id: "ref_1",
        entityId: "evt_1",
        entityType: "event",
        entityTitle: "UMak SIC General Assembly",
        role: "cover",
        isLocked: true,
      },
      {
        id: "ref_2",
        entityId: "cmp_1",
        entityType: "campaign",
        entityTitle: "Reminder: UMak SIC General Assembly this Saturday!",
        role: "banner",
        isLocked: true,
      },
    ],
  },
  {
    id: "ast_2",
    objectKey: "assets/documents/event-program-and-guidelines.pdf",
    originalFilename: "event-program-and-guidelines.pdf",
    mediaType: "application/pdf",
    format: "pdf",
    category: "document",
    byteSize: 430080,
    fileSizeFormatted: "420 KB",
    uploadedBy: "Charles Reyes",
    uploadedAt: "14 Oct 2026, 10:15 AM",
    pageCount: 4,
    sha256Hash: "8b1a9953c4611296a827abf8c47804d7e6e73720261520dfb26a17acb61fb570",
    url: "#",
    downloadCount: 88,
    references: [
      {
        id: "ref_3",
        entityId: "cmp_1",
        entityType: "campaign",
        entityTitle: "Reminder: UMak SIC General Assembly this Saturday!",
        role: "attachment",
        isLocked: true,
      },
    ],
  },
  {
    id: "ast_3",
    objectKey: "assets/banners/cloud-computing-cover.png",
    originalFilename: "cloud-computing-cover.png",
    mediaType: "image/png",
    format: "png",
    category: "image",
    byteSize: 2516582,
    fileSizeFormatted: "2.4 MB",
    uploadedBy: "Charles Reyes",
    uploadedAt: "12 Oct 2026, 03:45 PM",
    dimensions: "1920 × 1080 px",
    sha256Hash: "ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb",
    url: "/assets/events/event-cloud.png",
    previewUrl: "/assets/events/event-cloud.png",
    downloadCount: 19,
    references: [
      {
        id: "ref_4",
        entityId: "evt_2",
        entityType: "event",
        entityTitle: "Intro to Cloud Computing",
        role: "cover",
        isLocked: true,
      },
    ],
  },
  {
    id: "ast_4",
    objectKey: "assets/documents/speaker-profiles-deck.pdf",
    originalFilename: "speaker-profiles-deck.pdf",
    mediaType: "application/pdf",
    format: "pdf",
    category: "document",
    byteSize: 1153433,
    fileSizeFormatted: "1.1 MB",
    uploadedBy: "Charles Reyes",
    uploadedAt: "10 Oct 2026, 11:20 AM",
    pageCount: 12,
    sha256Hash: "f6c05763b6bc6b0d912443fe06fe518a45e227091cb9652c713be2be2780e0c9",
    url: "#",
    downloadCount: 34,
    references: [
      {
        id: "ref_5",
        entityId: "evt_4",
        entityType: "event",
        entityTitle: "UMak Tech Summit 2026",
        role: "attachment",
        isLocked: true,
      },
    ],
  },
  {
    id: "ast_5",
    objectKey: "assets/branding/sic-banner-hero.png",
    originalFilename: "sic-banner-hero.png",
    mediaType: "image/png",
    format: "png",
    category: "image",
    byteSize: 901120,
    fileSizeFormatted: "880 KB",
    uploadedBy: "Charles Reyes",
    uploadedAt: "08 Oct 2026, 02:10 PM",
    dimensions: "1200 × 500 px",
    sha256Hash: "9f83c6051f8ce0d0d5e03f2d0e9e8657a5c2d1b45ab3071749b8f16f28659ff3",
    url: "/assets/events/event-design.png",
    previewUrl: "/assets/events/event-design.png",
    downloadCount: 65,
    references: [
      {
        id: "ref_6",
        entityId: "evt_3",
        entityType: "event",
        entityTitle: "UI/UX Design Sprint",
        role: "cover",
        isLocked: true,
      },
    ],
  },
  {
    id: "ast_6",
    objectKey: "assets/branding/umak-sic-official-logo.png",
    originalFilename: "umak-sic-official-logo.png",
    mediaType: "image/png",
    format: "png",
    category: "image",
    byteSize: 327680,
    fileSizeFormatted: "320 KB",
    uploadedBy: "Charles Reyes",
    uploadedAt: "01 Oct 2026, 08:00 AM",
    dimensions: "512 × 512 px",
    sha256Hash: "1e25e377366f002b5e3630230c511f8b139b6acd8100c8e804eab979b6815d8f",
    url: "/assets/sic_logo.png",
    previewUrl: "/assets/sic_logo.png",
    downloadCount: 120,
    references: [
      {
        id: "ref_7",
        entityId: "evt_1",
        entityType: "event",
        entityTitle: "UMak SIC General Assembly",
        role: "general",
        isLocked: true,
      },
      {
        id: "ref_8",
        entityId: "evt_2",
        entityType: "event",
        entityTitle: "Intro to Cloud Computing",
        role: "general",
        isLocked: true,
      },
    ],
  },
  {
    id: "ast_7",
    objectKey: "assets/photos/quadrangle-event-photo.webp",
    originalFilename: "quadrangle-event-photo.webp",
    mediaType: "image/webp",
    format: "webp",
    category: "image",
    byteSize: 1992294,
    fileSizeFormatted: "1.9 MB",
    uploadedBy: "Charles Reyes",
    uploadedAt: "05 Oct 2026, 04:30 PM",
    dimensions: "1600 × 900 px",
    sha256Hash: "3b29c9a5b6f3c5b8e4e7d2a1b9f6c0a8e4d2b1c9a7e5f3d1b9c7e5a3b1d9f7c5",
    url: "/assets/events/event-summit.png",
    previewUrl: "/assets/events/event-summit.png",
    downloadCount: 8,
    references: [], // Unreferenced
  },
  {
    id: "ast_8",
    objectKey: "assets/documents/sample-attendance-roster-template.pdf",
    originalFilename: "sample-attendance-roster-template.pdf",
    mediaType: "application/pdf",
    format: "pdf",
    category: "document",
    byteSize: 184320,
    fileSizeFormatted: "180 KB",
    uploadedBy: "Charles Reyes",
    uploadedAt: "03 Oct 2026, 01:15 PM",
    pageCount: 2,
    sha256Hash: "7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b",
    url: "#",
    downloadCount: 15,
    references: [], // Unreferenced
  },
];

export const STORAGE_KPIS_DATA: StorageKpis = {
  totalBytesUsed: 9482865,
  totalBytesFormatted: "9.5 MB",
  storageQuotaBytes: 5368709120, // 5 GB
  storageQuotaFormatted: "5 GB",
  totalFilesCount: 8,
  imageCount: 5,
  documentCount: 3,
  referencedCount: 6,
  unusedCount: 2,
  storageHealthStatus: "healthy",
};
